"""empty message

Revision ID: 303924a24e63
Revises: 
Create Date: 2026-02-05 13:06:07.158383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '303924a24e63'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phash', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.drop_column('phash')

    # ### end Alembic commands ###
