"""add book model

Revision ID: 555b08ab19ef
Revises: 
Create Date: 2026-02-03 11:51:12.850171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '555b08ab19ef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('authors')
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('isbn', sa.String(length=13), nullable=False))
        batch_op.create_unique_constraint(None, ['isbn'])
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('price')
        batch_op.drop_column('author_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('price', sa.FLOAT(), nullable=False))
        batch_op.create_foreign_key(None, 'authors', ['author_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('isbn')
        batch_op.drop_column('author')

    op.create_table('authors',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('bio', sa.VARCHAR(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###
